In [69]:
# ASK USER TO ENTER NUMBERS
value1 = input("Please enter the first number choice, hint: it is the number between 2 and 4:\n")
value2 = input("Please enter your second number choice, hint: it is the number between 44 and 46:\n")
value3 = input("Please enter your third number choice, hint: it is the number between 82 and 84:\n")
value4 = input("Please enter your fourth number choice, hint: it is the number between 20 and 22:\n")

# SET THE VARIABLES
v1 = int(3)
v2 = int(45)
v3 = int(83)
v4 = int(21)

# IF AND ELSE SMENTS
if v1 == 3:
    print("You chose the correct number!")
else:
    print("Sorry you did not enter the correct value.")

if v2 == 45:
    print("You chose the correct number!")
else:
    print("Sorry you did not enter the correct values.")

if v3 == 83:
    print("You chose the correct number!")
else:
    print("Sorry you did not enter the correct values.")

if v4 == 21:
    print("You chose the correct number!")
else:
    print("Sorry you did not enter the correct values.")

print("Cogratulations, your responses have been saved to Numbers.txt")

# SAVE RESPONSES TO NUMBERS.TXT

my_file = open("Numbers.txt", "w")

my_file.write (value1)
my_file.write ("\n")
my_file.write (value2)
my_file.write  ("\n")
my_file.write (value3)
my_file.write  ("\n")
my_file.write (value4)

my_file.close()

You chose the correct number!
You chose the correct number!
You chose the correct number!
You chose the correct number!
Cogratulations, your responses have been saved to Numbers.txt


In [4]:
mark_grade = float(input("Please enter your mark in figures only: "))

if  mark_grade > 90 and mark_grade <=100:
    print ("Congratulations! You got an A+")
elif mark_grade >80 and mark_grade <=90:
    print ("Congratulations! You got an A")
elif mark_grade >70 and mark_grade <=80:
    print ("Congratulations! You got a B")
elif mark_grade >60 and mark_grade <=70:
    print ("Congratulations! You got a C")
elif mark_grade >50 and mark_grade <=60:
    print ("Congratulations! You got a D")
elif mark_grade >50 and mark_grade <=60:
    print ("You got an E!")
elif mark_grade >0 and mark_grade <=50:
    print ("You got an F!")
else:
    print("Unfortunately you need to enter a mark between 0 and 100")

Congratulations! You got a B


In [7]:
import numpy as np
Array = np.arange(10)
print("Array from 0 to 10:")
print(Array)

Array from 0 to 10:
[0 1 2 3 4 5 6 7 8 9]


In [15]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
bool_arr = np.ones((3, 3), dtype=bool)
print('2D Numpy Array: ')
print(bool_arr)

2D Numpy Array: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [29]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 == 1] = -1

print (a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [32]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,])
newArray = array.reshape (2,5)
print(newArray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[[ 116  122  128  134]
 [ 372  394  416  438]
 [ 628  666  704  742]
 [ 884  938  992 1046]]
[2000 2120 2240 2360]


In [69]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.column_stack((a,b))

print(c)

c = np.dot(a,b)

print(c)

e = np.sum(c, axis= 0)

print (e)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
130
130


In [75]:
a = np.array([1,2,3])

np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [45]:
a = np.vstack([1,2,3,4,5])
b = np.vstack([4,5,6,7,8,9])
c = np.delete (b, (0,1))
d = np.concatenate ((a,b))

print(d)

[[1]
 [2]
 [3]
 [4]
 [5]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [54]:
a = np.vstack([1,2,3,4,5])
b = np.vstack([4,5,6,7,8,9])
c = np.delete (b, (0,1))
d = np.concatenate ((a,b), axis = 0)

e=d[2]+[3]+[4]+[5]+[6]+[7]

print(e)

[28]
